### ISSUE TITLE
Siren sync

### ISSUE THREAD

**Issue by szajkok** [OfficerBozza/BozLights#18]
When a driver turns on the siren it seems that sometimes other players don't hear it - maybe a sync problem?

**Comment by DomTheFurry** [comment]
How long ago has this been happening? Haven't had this issue in any of my own or Bozza's servers.

**Comment by szajkok** [comment]
might be cause I added stage 3 check and siren park kill but I didn't really change the code that much... siren kill is a seperate feature that shouldn't affect anything, I would blame it on stage 3 check I guess

**Comment by szajkok** [comment]
so the added code looks like this:

function SirenParkKill(veh)
	local model = GetEntityModel(veh)
	for i = 1, #ModelsWithSirenParkKill, 1 do
		if model == GetHashKey(ModelsWithSirenParkKill[i]) then
			return true
		end
	end
	return false
end

Citizen.CreateThread(function()
	while true do
		Citizen.Wait(0)
		local ped = GetPlayerPed(-1)
		local veh = GetVehiclePedIsIn(ped, false)
		if  IsPedSittingInVehicle(ped, veh) and IsVehicleSirenOn(veh) and GetPedInVehicleSeat(veh, -1) == PlayerPedId() and SirenParkKill(veh) and IsControlPressed(0, 23) then
			SetLxSirenStateForVeh(veh, nstate)
			count_bcast_timer = delay_bcast_timer
			TriggerServerEvent('InteractSound_SV:PlayOnSource', 'shifterleo', 0.3)
			Citizen.Wait(2000)
		end
	end
end)

**Comment by szajkok** [comment]
also sometimes you need to press alt a few times so you can actually turn on your tones with 1, 2, 3 etc // plauyers will hear the siren if they turn it on themselves inside of the car - idk why

**Comment by szajkok** [comment]
alr so after replacing the script with the original version everything seems to work

**Comment by szajkok** [comment]
the only problem is that some players for some reason can't (actually one player) turn on the siren with the deafult key and I need to add the experimental feature so he can bind the key himself

**Comment by szajkok** [comment]
FIXEEED, gonna push a fork or sum like that so I can share the siren park kill function
